version: "2.4"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.25
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: EMS-NQN
    environment:
      MYSQL_DATABASE: 'vtv_database'
      MYSQL_USER: 'eselis'
      MYSQL_PASSWORD: 'eselis'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'